I am an exception thrown when there is a timeout while waiting for the synchronization of a future.