accessing
exceptionHandler: aHandler
	
	process exceptionHandler: aHandler